version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cakephp_app
      MYSQL_USER: cakeuser
      MYSQL_PASSWORD: cakepass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: cakephp_backend
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - ../backend:/var/www/html
    ports:
      - "8000:80"
    environment:
      - DB_HOST=mysql
      - DB_NAME=cakephp_app
      - DB_USER=cakeuser
      - DB_PASSWORD=cakepass
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: react_frontend
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ../front-end:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge